main = ".open-next/worker.js"
name = "notenextra"
pages_build_output_directory = ".vercel/output/static"
compatibility_date = "2025-02-13"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS" }
