export default {
   //index: "Course Description",
    "---":{
        type: 'separator'
    },
    Exam_reviews: "Exam reviews",
    CSE442T_L1: "Introduction to Cryptography (Lecture 1)",
    CSE442T_L2: "Introduction to Cryptography (Lecture 2)",
    CSE442T_L3: "Introduction to Cryptography (Lecture 3)",
    CSE442T_L4: "Introduction to Cryptography (Lecture 4)",
    CSE442T_L5: "Introduction to Cryptography (Lecture 5)",
    CSE442T_L6: "Introduction to Cryptography (Lecture 6)",
    CSE442T_L7: "Introduction to Cryptography (Lecture 7)",
    CSE442T_L8: "Introduction to Cryptography (Lecture 8)",
    CSE442T_L9: "Introduction to Cryptography (Lecture 9)",
    CSE442T_L10: "Introduction to Cryptography (Lecture 10)",
    CSE442T_L11: "Introduction to Cryptography (Lecture 11)",
    CSE442T_L12: "Introduction to Cryptography (Lecture 12)",
    CSE442T_L13: "Introduction to Cryptography (Lecture 13)",
    CSE442T_L14: "Introduction to Cryptography (Lecture 14)",
    CSE442T_L15: "Introduction to Cryptography (Lecture 15)",
    CSE442T_L16: "Introduction to Cryptography (Lecture 16)",
    CSE442T_L17: "Introduction to Cryptography (Lecture 17)",
    CSE442T_L18: "Introduction to Cryptography (Lecture 18)",
    CSE442T_L19: "Introduction to Cryptography (Lecture 19)",
    CSE442T_L20: "Introduction to Cryptography (Lecture 20)",
    CSE442T_L21: "Introduction to Cryptography (Lecture 21)",
    CSE442T_L22: "Introduction to Cryptography (Lecture 22)",
    CSE442T_L23: "Introduction to Cryptography (Lecture 23)",
    CSE442T_L24: "Introduction to Cryptography (Lecture 24)"
}
