export default {
   //index: "Course Description",
    "---": {
        type: 'separator'
    },
    Lecture_1: "Elementary to Intermediate Statistics and Data Analysis (Lecture 1)",
    Lecture_2: "Elementary to Intermediate Statistics and Data Analysis (Lecture 2)",
    Lecture_3: "Elementary to Intermediate Statistics and Data Analysis (Lecture 3)",
    Lecture_4: "Elementary to Intermediate Statistics and Data Analysis (Lecture 4)",
    Lecture_5: "Elementary to Intermediate Statistics and Data Analysis (Lecture 5)",
    Lecture_6: "Elementary to Intermediate Statistics and Data Analysis (Lecture 6)",
    Lecture_7: "Elementary to Intermediate Statistics and Data Analysis (Lecture 7)",
    Lecture_8: "Elementary to Intermediate Statistics and Data Analysis (Lecture 8)",
    Lecture_9: "Elementary to Intermediate Statistics and Data Analysis (Lecture 9)",
    Lecture_10: "Elementary to Intermediate Statistics and Data Analysis (Lecture 10)",
    Lecture_11: "Elementary to Intermediate Statistics and Data Analysis (Lecture 11)",
    Lecture_12: "Elementary to Intermediate Statistics and Data Analysis (Lecture 12)",
    Lecture_13: "Elementary to Intermediate Statistics and Data Analysis (Lecture 13)",
    Lecture_14: "Elementary to Intermediate Statistics and Data Analysis (Lecture 14)",
    Lecture_15: "Elementary to Intermediate Statistics and Data Analysis (Lecture 15)",
    Lecture_16: "Elementary to Intermediate Statistics and Data Analysis (Lecture 16)",
    Lecture_17: "Elementary to Intermediate Statistics and Data Analysis (Lecture 17)",
    Lecture_18: "Elementary to Intermediate Statistics and Data Analysis (Lecture 18)",
    Lecture_19: "Elementary to Intermediate Statistics and Data Analysis (Lecture 19)",
    Lecture_20: "Elementary to Intermediate Statistics and Data Analysis (Lecture 20)",
    Lecture_21: "Elementary to Intermediate Statistics and Data Analysis (Lecture 21)",
    Lecture_22: "Elementary to Intermediate Statistics and Data Analysis (Lecture 22)",
    Lecture_23: "Elementary to Intermediate Statistics and Data Analysis (Lecture 23)",
    Lecture_24: "Elementary to Intermediate Statistics and Data Analysis (Lecture 24)",
    Lecture_25: "Elementary to Intermediate Statistics and Data Analysis (Lecture 25)",
    Lecture_26: "Elementary to Intermediate Statistics and Data Analysis (Lecture 26)",
    Lecture_27: "Elementary to Intermediate Statistics and Data Analysis (Lecture 27)",
    Lecture_28: "Elementary to Intermediate Statistics and Data Analysis (Lecture 28)",
    Lecture_29: "Elementary to Intermediate Statistics and Data Analysis (Lecture 29)",
    Lecture_30: "Elementary to Intermediate Statistics and Data Analysis (Lecture 30)",
    Lecture_31: "Elementary to Intermediate Statistics and Data Analysis (Lecture 31)",
    Lecture_32: "Elementary to Intermediate Statistics and Data Analysis (Lecture 32)",
    Lecture_33: "Elementary to Intermediate Statistics and Data Analysis (Lecture 33)",
    Lecture_34: "Elementary to Intermediate Statistics and Data Analysis (Lecture 34)",
    Lecture_35: "Elementary to Intermediate Statistics and Data Analysis (Lecture 35)",
    Lecture_36: "Elementary to Intermediate Statistics and Data Analysis (Lecture 36)",
    Lecture_37: "Elementary to Intermediate Statistics and Data Analysis (Lecture 37)",
    Lecture_38: "Elementary to Intermediate Statistics and Data Analysis (Lecture 38)",
    Lecture_39: "Elementary to Intermediate Statistics and Data Analysis (Lecture 39)",
    Lecture_40: "Elementary to Intermediate Statistics and Data Analysis (Lecture 40)"
}