export default {
    index: "Course Description",
    "---": {
        type: 'separator'
    },
    Math3200_L1: "Elementary to Intermediate Statistics and Data Analysis (Lecture 1)",
    Math3200_L2: "Elementary to Intermediate Statistics and Data Analysis (Lecture 2)",
    Math3200_L3: "Elementary to Intermediate Statistics and Data Analysis (Lecture 3)",
    Math3200_L4: "Elementary to Intermediate Statistics and Data Analysis (Lecture 4)",
    Math3200_L5: "Elementary to Intermediate Statistics and Data Analysis (Lecture 5)",
    Math3200_L6: "Elementary to Intermediate Statistics and Data Analysis (Lecture 6)",
    Math3200_L7: "Elementary to Intermediate Statistics and Data Analysis (Lecture 7)",
    Math3200_L8: "Elementary to Intermediate Statistics and Data Analysis (Lecture 8)",
    Math3200_L9: "Elementary to Intermediate Statistics and Data Analysis (Lecture 9)",
    Math3200_L10: "Elementary to Intermediate Statistics and Data Analysis (Lecture 10)",
    Math3200_L11: "Elementary to Intermediate Statistics and Data Analysis (Lecture 11)",
    Math3200_L12: "Elementary to Intermediate Statistics and Data Analysis (Lecture 12)",
    Math3200_L13: "Elementary to Intermediate Statistics and Data Analysis (Lecture 13)",
    Math3200_L14: "Elementary to Intermediate Statistics and Data Analysis (Lecture 14)",
    Math3200_L15: "Elementary to Intermediate Statistics and Data Analysis (Lecture 15)",
    Math3200_L16: "Elementary to Intermediate Statistics and Data Analysis (Lecture 16)",
    Math3200_L17: "Elementary to Intermediate Statistics and Data Analysis (Lecture 17)",
    Math3200_L18: "Elementary to Intermediate Statistics and Data Analysis (Lecture 18)",
    Math3200_L19: "Elementary to Intermediate Statistics and Data Analysis (Lecture 19)",
    Math3200_L20: "Elementary to Intermediate Statistics and Data Analysis (Lecture 20)",
    Math3200_L21: "Elementary to Intermediate Statistics and Data Analysis (Lecture 21)",
    Math3200_L22: "Elementary to Intermediate Statistics and Data Analysis (Lecture 22)",
    Math3200_L23: "Elementary to Intermediate Statistics and Data Analysis (Lecture 23)",
    Math3200_L24: "Elementary to Intermediate Statistics and Data Analysis (Lecture 24)",
    Math3200_L25: "Elementary to Intermediate Statistics and Data Analysis (Lecture 25)",
    Math3200_L26: "Elementary to Intermediate Statistics and Data Analysis (Lecture 26)",
    Math3200_L27: "Elementary to Intermediate Statistics and Data Analysis (Lecture 27)",
    Math3200_L28: "Elementary to Intermediate Statistics and Data Analysis (Lecture 28)",
    Math3200_L29: "Elementary to Intermediate Statistics and Data Analysis (Lecture 29)",
    Math3200_L30: "Elementary to Intermediate Statistics and Data Analysis (Lecture 30)",
    Math3200_L31: "Elementary to Intermediate Statistics and Data Analysis (Lecture 31)",
    Math3200_L32: "Elementary to Intermediate Statistics and Data Analysis (Lecture 32)",
    Math3200_L33: "Elementary to Intermediate Statistics and Data Analysis (Lecture 33)",
    Math3200_L34: "Elementary to Intermediate Statistics and Data Analysis (Lecture 34)",
    Math3200_L35: "Elementary to Intermediate Statistics and Data Analysis (Lecture 35)",
    Math3200_L36: "Elementary to Intermediate Statistics and Data Analysis (Lecture 36)",
    Math3200_L37: "Elementary to Intermediate Statistics and Data Analysis (Lecture 37)",
    Math3200_L38: "Elementary to Intermediate Statistics and Data Analysis (Lecture 38)",
    Math3200_L39: "Elementary to Intermediate Statistics and Data Analysis (Lecture 39)",
    Math3200_L40: "Elementary to Intermediate Statistics and Data Analysis (Lecture 40)"
}